version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:8.12.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=trial
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.12.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  neo4j:
    image: neo4j:5.16.0
    environment:
      - NEO4J_AUTH=none
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neodata:/data

volumes:
  esdata:
  neodata: